# =============================================================
# Hi-Tech Waste Management — Database Agent
# AI-powered natural language database operations
# =============================================================

from __future__ import annotations

import json
import logging
import uuid
from datetime import date, datetime, time
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Type, Union

from pydantic import BaseModel, ConfigDict, Field, create_model
from sqlalchemy import select, and_, or_, func
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import DeclarativeBase

from database import Base
from models.client import Client, ClientCreate, ClientUpdate, ClientWasteStream, ClientWasteStreamCreate
from models.job import Job, JobCreate, JobUpdate, RecurringJobTemplate, RecurringJobTemplateCreate
from models.vehicle import Vehicle, VehicleCreate, VehicleUpdate, Trip, TripCreate
from models.user import User, UserCreate, UserUpdate
from models.scheduled_waste import ScheduledWasteBatch, ScheduledWasteBatchCreate
from models.esg import CarbonRecord, CarbonRecordCreate
from models.recyclable import RecyclableRecord, RecyclableRecordCreate
from models.equipment import Container, ContainerCreate, CompactionMachine, CompactionMachineCreate
from models.bsf import BSFBatch, BSFBatchCreate
from models.destruction import DestructionJob, DestructionJobCreate

logger = logging.getLogger(__name__)


# =============================================================
# Enums and Constants
# =============================================================

class DatabaseAction(str, Enum):
    """Supported database actions."""
    QUERY = "query"           # Read/fetch records
    CREATE = "create"         # Create new record
    UPDATE = "update"         # Update existing record
    DELETE = "delete"         # Delete record
    LIST = "list"             # List records with filters
    GET_SCHEMA = "get_schema" # Get entity schema info


class EntityType(str, Enum):
    """Supported entity types for database operations."""
    CLIENT = "client"
    CLIENT_WASTE_STREAM = "client_waste_stream"
    JOB = "job"
    RECURRING_JOB_TEMPLATE = "recurring_job_template"
    VEHICLE = "vehicle"
    TRIP = "trip"
    USER = "user"
    SCHEDULED_WASTE_BATCH = "scheduled_waste_batch"
    CARBON_RECORD = "carbon_record"
    RECYCLABLE_RECORD = "recyclable_record"
    CONTAINER = "container"
    COMPACTION_MACHINE = "compaction_machine"
    BSF_BATCH = "bsf_batch"
    DESTRUCTION_JOB = "destruction_job"


# Mapping of entity types to their ORM models and schemas
ENTITY_METADATA: Dict[str, Dict[str, Any]] = {
    EntityType.CLIENT: {
        "model": Client,
        "create_schema": ClientCreate,
        "update_schema": ClientUpdate,
        "required_fields": ["company_name"],
        "searchable_fields": ["company_name", "pic_name", "pic_email", "ssm_number"],
        "display_name": "Client",
        "description": "A waste management customer/company",
    },
    EntityType.CLIENT_WASTE_STREAM: {
        "model": ClientWasteStream,
        "create_schema": ClientWasteStreamCreate,
        "required_fields": ["client_id", "waste_type"],
        "searchable_fields": ["waste_type"],
        "display_name": "Client Waste Stream",
        "description": "A specific waste type generated by a client",
    },
    EntityType.JOB: {
        "model": Job,
        "create_schema": JobCreate,
        "update_schema": JobUpdate,
        "required_fields": ["client_id", "job_type"],
        "searchable_fields": ["job_number", "job_type", "status"],
        "display_name": "Job",
        "description": "A waste collection or service job",
    },
    EntityType.RECURRING_JOB_TEMPLATE: {
        "model": RecurringJobTemplate,
        "create_schema": RecurringJobTemplateCreate,
        "required_fields": ["name", "client_id", "job_type", "recurrence_rule"],
        "searchable_fields": ["name", "job_type"],
        "display_name": "Recurring Job Template",
        "description": "Template for automatically generating recurring jobs",
    },
    EntityType.VEHICLE: {
        "model": Vehicle,
        "create_schema": VehicleCreate,
        "update_schema": VehicleUpdate,
        "required_fields": ["registration", "vehicle_type"],
        "searchable_fields": ["registration", "vehicle_type", "make", "model"],
        "display_name": "Vehicle",
        "description": "A fleet vehicle",
    },
    EntityType.TRIP: {
        "model": Trip,
        "create_schema": TripCreate,
        "required_fields": ["vehicle_id"],
        "searchable_fields": [],
        "display_name": "Trip",
        "description": "A vehicle trip for a job",
    },
    EntityType.USER: {
        "model": User,
        "create_schema": UserCreate,
        "update_schema": UserUpdate,
        "required_fields": ["email", "full_name", "role"],
        "searchable_fields": ["email", "full_name"],
        "display_name": "User",
        "description": "A system user (staff, driver, admin)",
    },
    EntityType.SCHEDULED_WASTE_BATCH: {
        "model": ScheduledWasteBatch,
        "create_schema": ScheduledWasteBatchCreate,
        "required_fields": ["client_id", "sw_code", "waste_description", "quantity_kg"],
        "searchable_fields": ["sw_code", "waste_description", "status"],
        "display_name": "Scheduled Waste Batch",
        "description": "A batch of scheduled (hazardous) waste",
    },
    EntityType.CARBON_RECORD: {
        "model": CarbonRecord,
        "create_schema": CarbonRecordCreate,
        "required_fields": ["client_id", "waste_type", "quantity_kg"],
        "searchable_fields": ["waste_type"],
        "display_name": "Carbon Record",
        "description": "A carbon footprint record",
    },
    EntityType.RECYCLABLE_RECORD: {
        "model": RecyclableRecord,
        "create_schema": RecyclableRecordCreate,
        "required_fields": ["client_id", "material_type", "quantity_kg"],
        "searchable_fields": ["material_type"],
        "display_name": "Recyclable Record",
        "description": "A recyclable material recovery record",
    },
    EntityType.CONTAINER: {
        "model": Container,
        "create_schema": ContainerCreate,
        "required_fields": ["container_number", "size_yards", "client_id"],
        "searchable_fields": ["container_number", "status"],
        "display_name": "Container",
        "description": "A waste container/skip",
    },
    EntityType.COMPACTION_MACHINE: {
        "model": CompactionMachine,
        "create_schema": CompactionMachineCreate,
        "required_fields": ["machine_id", "machine_type", "location"],
        "searchable_fields": ["machine_id", "machine_type", "location"],
        "display_name": "Compaction Machine",
        "description": "A compaction machine at a client site",
    },
    EntityType.BSF_BATCH: {
        "model": BSFBatch,
        "create_schema": BSFBatchCreate,
        "required_fields": ["intake_date", "food_waste_kg"],
        "searchable_fields": ["status", "contamination_level"],
        "display_name": "BSF Batch",
        "description": "A Black Soldier Fly bioconversion batch",
    },
    EntityType.DESTRUCTION_JOB: {
        "model": DestructionJob,
        "create_schema": DestructionJobCreate,
        "required_fields": ["client_id", "destruction_type", "scheduled_date"],
        "searchable_fields": ["destruction_type", "status"],
        "display_name": "Destruction Job",
        "description": "A witnessed destruction job",
    },
}


# =============================================================
# Pydantic Models for Database Agent
# =============================================================

class DatabaseOperationRequest(BaseModel):
    """Request to perform a database operation."""
    action: DatabaseAction = Field(..., description="The action to perform")
    entity_type: EntityType = Field(..., description="The entity type to operate on")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Filters for query/list operations")
    data: Optional[Dict[str, Any]] = Field(default=None, description="Data for create/update operations")
    entity_id: Optional[str] = Field(default=None, description="Entity UUID for update/delete/get operations")
    limit: Optional[int] = Field(default=50, ge=1, le=200, description="Limit for list operations")
    offset: Optional[int] = Field(default=0, ge=0, description="Offset for list operations")


class DatabaseOperationResult(BaseModel):
    """Result of a database operation."""
    success: bool
    action: DatabaseAction
    entity_type: str
    message: str
    data: Optional[Any] = None
    error: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


class EntitySchemaInfo(BaseModel):
    """Schema information for an entity type."""
    entity_type: str
    display_name: str
    description: str
    required_fields: List[str]
    optional_fields: List[str]
    field_types: Dict[str, str]
    example_data: Dict[str, Any]


class PendingOperation(BaseModel):
    """Tracks a pending database operation awaiting user confirmation or more data."""
    operation_id: str
    action: DatabaseAction
    entity_type: EntityType
    collected_data: Dict[str, Any]
    missing_required_fields: List[str]
    proposed_data: Optional[Dict[str, Any]] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now())


# =============================================================
# Database Agent Class
# =============================================================

class DatabaseAgent:
    """
    AI agent that can perform database operations based on natural language.
    
    Supports:
    - Querying records with natural language filters
    - Creating new records with field validation
    - Updating existing records
    - Deleting records
    - Schema introspection
    """
    
    def __init__(self, db: AsyncSession, current_user: Dict[str, Any]):
        self.db = db
        self.current_user = current_user
        self.user_id = uuid.UUID(current_user.get("sub")) if current_user.get("sub") else None
        self.user_role = current_user.get("role", "")
        self._pending_operations: Dict[str, PendingOperation] = {}
    
    # ---------------------------------------------------------
    # Public API
    # ---------------------------------------------------------
    
    async def execute_operation(
        self, 
        request: DatabaseOperationRequest
    ) -> DatabaseOperationResult:
        """Execute a database operation based on the request."""
        try:
            if request.action == DatabaseAction.QUERY:
                return await self._query_entity(request)
            elif request.action == DatabaseAction.LIST:
                return await self._list_entities(request)
            elif request.action == DatabaseAction.CREATE:
                return await self._create_entity(request)
            elif request.action == DatabaseAction.UPDATE:
                return await self._update_entity(request)
            elif request.action == DatabaseAction.DELETE:
                return await self._delete_entity(request)
            elif request.action == DatabaseAction.GET_SCHEMA:
                return await self._get_schema(request)
            else:
                return DatabaseOperationResult(
                    success=False,
                    action=request.action,
                    entity_type=request.entity_type.value,
                    message=f"Unsupported action: {request.action}",
                    error="UNSUPPORTED_ACTION"
                )
        except Exception as exc:
            logger.exception("Database operation failed")
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Operation failed: {str(exc)}",
                error=str(exc)
            )
    
    async def get_entity_schema(self, entity_type: EntityType) -> EntitySchemaInfo:
        """Get schema information for an entity type."""
        meta = ENTITY_METADATA.get(entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {entity_type}")
        
        create_schema = meta.get("create_schema")
        if not create_schema:
            raise ValueError(f"No create schema for entity type: {entity_type}")
        
        # Extract field information from Pydantic schema
        schema = create_schema.model_json_schema()
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        
        field_types = {}
        optional_fields = []
        example_data = {}
        
        for field_name, field_info in properties.items():
            if field_name == "waste_streams":  # Special case for client
                continue
                
            field_type = field_info.get("type", "unknown")
            if field_type == "string" and "format" in field_info:
                if field_info["format"] == "uuid":
                    field_type = "uuid"
                elif field_info["format"] == "date":
                    field_type = "date"
                elif field_info["format"] == "date-time":
                    field_type = "datetime"
            elif field_type == "number":
                field_type = "decimal"
            elif field_type == "integer":
                field_type = "int"
            elif field_type == "boolean":
                field_type = "bool"
            
            field_types[field_name] = field_type
            
            if field_name not in required:
                optional_fields.append(field_name)
            
            # Generate example data
            if field_type == "string":
                example_data[field_name] = f"example_{field_name}"
            elif field_type == "uuid":
                example_data[field_name] = str(uuid.uuid4())
            elif field_type == "date":
                example_data[field_name] = "2024-01-15"
            elif field_type == "datetime":
                example_data[field_name] = "2024-01-15T10:30:00Z"
            elif field_type == "decimal":
                example_data[field_name] = 100.50
            elif field_type == "int":
                example_data[field_name] = 42
            elif field_type == "bool":
                example_data[field_name] = True
        
        return EntitySchemaInfo(
            entity_type=entity_type.value,
            display_name=meta["display_name"],
            description=meta["description"],
            required_fields=meta.get("required_fields", []),
            optional_fields=optional_fields,
            field_types=field_types,
            example_data=example_data
        )
    
    def create_pending_operation(
        self,
        action: DatabaseAction,
        entity_type: EntityType,
        collected_data: Dict[str, Any]
    ) -> PendingOperation:
        """Create a pending operation to track multi-step data collection."""
        # Find missing required fields
        meta = ENTITY_METADATA.get(entity_type, {})
        required_fields = meta.get("required_fields", [])
        missing = [f for f in required_fields if f not in collected_data or collected_data[f] is None]
        
        pending = PendingOperation(
            operation_id=str(uuid.uuid4()),
            action=action,
            entity_type=entity_type,
            collected_data=collected_data,
            missing_required_fields=missing
        )
        self._pending_operations[pending.operation_id] = pending
        return pending
    
    def get_pending_operation(self, operation_id: str) -> Optional[PendingOperation]:
        """Get a pending operation by ID."""
        return self._pending_operations.get(operation_id)
    
    def update_pending_operation(
        self, 
        operation_id: str, 
        new_data: Dict[str, Any]
    ) -> Optional[PendingOperation]:
        """Update a pending operation with new data."""
        pending = self._pending_operations.get(operation_id)
        if not pending:
            return None
        
        pending.collected_data.update(new_data)
        
        # Recalculate missing fields
        meta = ENTITY_METADATA.get(pending.entity_type, {})
        required_fields = meta.get("required_fields", [])
        pending.missing_required_fields = [
            f for f in required_fields 
            if f not in pending.collected_data or pending.collected_data[f] is None
        ]
        
        return pending
    
    def remove_pending_operation(self, operation_id: str) -> bool:
        """Remove a pending operation."""
        if operation_id in self._pending_operations:
            del self._pending_operations[operation_id]
            return True
        return False
    
    # ---------------------------------------------------------
    # Private Implementation
    # ---------------------------------------------------------
    
    async def _query_entity(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """Query a specific entity by ID or filters."""
        meta = ENTITY_METADATA.get(request.entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {request.entity_type}")
        
        model = meta["model"]
        
        # Build query
        stmt = select(model)
        
        if request.entity_id:
            # Query by ID
            try:
                entity_uuid = uuid.UUID(request.entity_id)
                stmt = stmt.where(model.id == entity_uuid)
            except ValueError:
                return DatabaseOperationResult(
                    success=False,
                    action=request.action,
                    entity_type=request.entity_type.value,
                    message=f"Invalid UUID: {request.entity_id}",
                    error="INVALID_UUID"
                )
        elif request.filters:
            # Apply filters
            filters = []
            for field, value in request.filters.items():
                if hasattr(model, field):
                    column = getattr(model, field)
                    if isinstance(value, str) and "%" in value:
                        filters.append(column.ilike(value))
                    else:
                        filters.append(column == value)
            if filters:
                stmt = stmt.where(and_(*filters))
        
        result = await self.db.execute(stmt)
        entities = result.scalars().all()
        
        # Convert to dict for serialization
        data = []
        for entity in entities:
            entity_dict = await self._entity_to_dict(entity)
            data.append(entity_dict)
        
        return DatabaseOperationResult(
            success=True,
            action=request.action,
            entity_type=request.entity_type.value,
            message=f"Found {len(data)} {request.entity_type.value}(s)",
            data=data,
            metadata={"count": len(data)}
        )
    
    async def _list_entities(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """List entities with pagination."""
        meta = ENTITY_METADATA.get(request.entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {request.entity_type}")
        
        model = meta["model"]
        
        # Build query
        stmt = select(model)
        
        # Apply filters if provided
        if request.filters:
            filters = []
            for field, value in request.filters.items():
                if hasattr(model, field):
                    column = getattr(model, field)
                    if isinstance(value, str):
                        filters.append(column.ilike(f"%{value}%"))
                    else:
                        filters.append(column == value)
            if filters:
                stmt = stmt.where(and_(*filters))
        
        # Get total count
        count_stmt = select(func.count()).select_from(stmt.subquery())
        total_result = await self.db.execute(count_stmt)
        total = total_result.scalar_one()
        
        # Apply pagination
        stmt = stmt.offset(request.offset or 0).limit(request.limit or 50)
        
        result = await self.db.execute(stmt)
        entities = result.scalars().all()
        
        # Convert to dict
        data = []
        for entity in entities:
            entity_dict = await self._entity_to_dict(entity)
            data.append(entity_dict)
        
        return DatabaseOperationResult(
            success=True,
            action=request.action,
            entity_type=request.entity_type.value,
            message=f"Retrieved {len(data)} {request.entity_type.value}(s)",
            data=data,
            metadata={
                "total": total,
                "offset": request.offset or 0,
                "limit": request.limit or 50
            }
        )
    
    async def _create_entity(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """Create a new entity."""
        meta = ENTITY_METADATA.get(request.entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {request.entity_type}")
        
        model = meta["model"]
        create_schema = meta.get("create_schema")
        
        if not create_schema:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Create not supported for {request.entity_type.value}",
                error="CREATE_NOT_SUPPORTED"
            )
        
        if not request.data:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message="No data provided for creation",
                error="NO_DATA"
            )
        
        # Validate required fields
        required_fields = meta.get("required_fields", [])
        missing = [f for f in required_fields if f not in request.data or request.data[f] is None]
        if missing:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Missing required fields: {', '.join(missing)}",
                error="MISSING_REQUIRED_FIELDS",
                metadata={"missing_fields": missing}
            )
        
        # Parse and validate data using Pydantic schema
        try:
            validated_data = create_schema(**request.data)
        except Exception as exc:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Validation error: {str(exc)}",
                error="VALIDATION_ERROR"
            )
        
        # Create entity
        try:
            # Convert Pydantic model to dict, handling special types
            entity_data = self._prepare_entity_data(validated_data.model_dump())
            entity = model(**entity_data)
            
            self.db.add(entity)
            await self.db.flush()
            await self.db.refresh(entity)
            
            entity_dict = await self._entity_to_dict(entity)
            
            return DatabaseOperationResult(
                success=True,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"{meta['display_name']} created successfully",
                data=entity_dict,
                metadata={"id": str(entity.id)}
            )
        except Exception as exc:
            await self.db.rollback()
            raise
    
    async def _update_entity(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """Update an existing entity."""
        if not request.entity_id:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message="Entity ID is required for update",
                error="MISSING_ENTITY_ID"
            )
        
        meta = ENTITY_METADATA.get(request.entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {request.entity_type}")
        
        model = meta["model"]
        
        try:
            entity_uuid = uuid.UUID(request.entity_id)
        except ValueError:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Invalid UUID: {request.entity_id}",
                error="INVALID_UUID"
            )
        
        # Fetch entity
        result = await self.db.execute(select(model).where(model.id == entity_uuid))
        entity = result.scalar_one_or_none()
        
        if not entity:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"{meta['display_name']} with ID {request.entity_id} not found",
                error="NOT_FOUND"
            )
        
        if not request.data:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message="No update data provided",
                error="NO_DATA"
            )
        
        # Update fields
        try:
            for field, value in request.data.items():
                if hasattr(entity, field):
                    # Handle UUID fields
                    if field.endswith("_id") and value is not None and isinstance(value, str):
                        try:
                            value = uuid.UUID(value)
                        except ValueError:
                            pass
                    setattr(entity, field, value)
            
            await self.db.flush()
            await self.db.refresh(entity)
            
            entity_dict = await self._entity_to_dict(entity)
            
            return DatabaseOperationResult(
                success=True,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"{meta['display_name']} updated successfully",
                data=entity_dict
            )
        except Exception as exc:
            await self.db.rollback()
            raise
    
    async def _delete_entity(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """Delete an entity."""
        if not request.entity_id:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message="Entity ID is required for deletion",
                error="MISSING_ENTITY_ID"
            )
        
        meta = ENTITY_METADATA.get(request.entity_type)
        if not meta:
            raise ValueError(f"Unknown entity type: {request.entity_type}")
        
        model = meta["model"]
        
        try:
            entity_uuid = uuid.UUID(request.entity_id)
        except ValueError:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"Invalid UUID: {request.entity_id}",
                error="INVALID_UUID"
            )
        
        # Fetch entity
        result = await self.db.execute(select(model).where(model.id == entity_uuid))
        entity = result.scalar_one_or_none()
        
        if not entity:
            return DatabaseOperationResult(
                success=False,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"{meta['display_name']} with ID {request.entity_id} not found",
                error="NOT_FOUND"
            )
        
        try:
            # Get identifying info before deletion
            entity_name = getattr(entity, 'company_name', None) or \
                         getattr(entity, 'job_number', None) or \
                         getattr(entity, 'registration', None) or \
                         str(entity.id)
            
            await self.db.delete(entity)
            await self.db.flush()
            
            return DatabaseOperationResult(
                success=True,
                action=request.action,
                entity_type=request.entity_type.value,
                message=f"{meta['display_name']} '{entity_name}' deleted successfully",
                data={"deleted_id": request.entity_id, "name": entity_name}
            )
        except Exception as exc:
            await self.db.rollback()
            raise
    
    async def _get_schema(self, request: DatabaseOperationRequest) -> DatabaseOperationResult:
        """Get schema information for an entity type."""
        schema_info = await self.get_entity_schema(request.entity_type)
        
        return DatabaseOperationResult(
            success=True,
            action=request.action,
            entity_type=request.entity_type.value,
            message=f"Schema for {request.entity_type.value}",
            data=schema_info.model_dump()
        )
    
    async def _entity_to_dict(self, entity: Any) -> Dict[str, Any]:
        """Convert an SQLAlchemy entity to a dictionary."""
        result = {}
        for column in entity.__table__.columns:
            value = getattr(entity, column.name)
            if value is None:
                result[column.name] = None
            elif isinstance(value, uuid.UUID):
                result[column.name] = str(value)
            elif isinstance(value, datetime):
                result[column.name] = value.isoformat()
            elif isinstance(value, date):
                result[column.name] = value.isoformat()
            elif isinstance(value, time):
                result[column.name] = value.isoformat()
            elif isinstance(value, Decimal):
                result[column.name] = float(value)
            else:
                result[column.name] = value
        return result
    
    def _prepare_entity_data(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Prepare entity data, converting string UUIDs to UUID objects."""
        result = {}
        for key, value in data.items():
            if value is None:
                result[key] = None
            elif key.endswith("_id") and isinstance(value, str):
                try:
                    result[key] = uuid.UUID(value)
                except ValueError:
                    result[key] = value
            elif isinstance(value, str):
                # Try to detect and convert dates
                if len(value) == 10 and value.count("-") == 2:
                    try:
                        result[key] = date.fromisoformat(value)
                    except ValueError:
                        result[key] = value
                else:
                    result[key] = value
            else:
                result[key] = value
        return result


# =============================================================
# Function Calling Schema for LLM
# =============================================================

DB_AGENT_FUNCTIONS = [
    {
        "name": "query_database",
        "description": "Query the database for records. Use for searching, finding specific records, or getting details.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The type of entity to query"
                },
                "filters": {
                    "type": "object",
                    "description": "Filters to apply (field -> value). Use partial strings for text search."
                },
                "entity_id": {
                    "type": "string",
                    "description": "Specific UUID to fetch (optional)"
                }
            },
            "required": ["entity_type"]
        }
    },
    {
        "name": "list_database",
        "description": "List records with pagination. Use for getting multiple records or browsing.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The type of entity to list"
                },
                "filters": {
                    "type": "object",
                    "description": "Optional filters to apply"
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum records to return (1-200)",
                    "default": 50
                }
            },
            "required": ["entity_type"]
        }
    },
    {
        "name": "create_database",
        "description": "Create a new record in the database. Only call this when you have ALL required fields.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The type of entity to create"
                },
                "data": {
                    "type": "object",
                    "description": "The data for the new record. Must include all required fields."
                }
            },
            "required": ["entity_type", "data"]
        }
    },
    {
        "name": "update_database",
        "description": "Update an existing record. Only call this when you have the entity_id and the fields to update.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The type of entity to update"
                },
                "entity_id": {
                    "type": "string",
                    "description": "The UUID of the entity to update"
                },
                "data": {
                    "type": "object",
                    "description": "The fields to update"
                }
            },
            "required": ["entity_type", "entity_id", "data"]
        }
    },
    {
        "name": "delete_database",
        "description": "Delete a record from the database. Use with caution - confirm with user first.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The type of entity to delete"
                },
                "entity_id": {
                    "type": "string",
                    "description": "The UUID of the entity to delete"
                }
            },
            "required": ["entity_type", "entity_id"]
        }
    },
    {
        "name": "get_schema",
        "description": "Get the schema/field information for an entity type. Use when you need to know what fields are required.",
        "parameters": {
            "type": "object",
            "properties": {
                "entity_type": {
                    "type": "string",
                    "enum": [e.value for e in EntityType],
                    "description": "The entity type to get schema for"
                }
            },
            "required": ["entity_type"]
        }
    }
]


def get_database_agent_system_prompt() -> str:
    """Get the system prompt for the database agent capability."""
    return """You are HiTech AI Database Assistant. You have the ability to read from and write to the Hi-Tech Waste Management database.

CAPABILITIES:
1. Query records - Search for and retrieve data
2. List records - Browse multiple records with filters
3. Create records - Add new clients, jobs, vehicles, etc.
4. Update records - Modify existing data
5. Delete records - Remove records (use cautiously)
6. Get schema - Check what fields are required/optional

AVAILABLE ENTITIES:
- client: Waste management customers/companies
- job: Waste collection or service jobs
- vehicle: Fleet vehicles (trucks, compactors, etc.)
- user: Staff, drivers, administrators
- scheduled_waste_batch: Hazardous/scheduled waste batches
- carbon_record: Carbon footprint records
- recyclable_record: Recyclable material recovery
- container: Waste containers/skips
- compaction_machine: On-site compaction equipment
- bsf_batch: Black Soldier Fly bioconversion batches
- destruction_job: Witnessed destruction jobs
- client_waste_stream: Waste types per client
- recurring_job_template: Templates for recurring jobs
- trip: Vehicle trips

GUIDELINES:
1. For CREATE operations, ALWAYS call get_schema first to check required fields
2. Collect ALL required fields from the user before calling create_database
3. If the user provides partial information, ask for the missing required fields
4. For UPDATE/DELETE, always confirm the entity_id (UUID) first by querying
5. Present data in a clear, formatted way
6. Be helpful and suggest related actions

When the user asks to create something:
1. Call get_schema to see required fields
2. Ask the user for any missing required information
3. Only call create_database when you have all required data
4. Confirm the creation with the user

When the user asks to find/query something:
1. Use query_database or list_database
2. Present results clearly
3. Offer to refine the search or perform actions on results
"""
